export enum SnippetLanguage {
  TYPESCRIPT = 'typescript',
  JAVASCRIPT = 'javascript',
  PYTHON = 'python',
  JAVA = 'java',
  CSHARP = 'csharp',
  GO = 'go',
  RUST = 'rust',
  SWIFT = 'swift',
  KOTLIN = 'kotlin',
  DART = 'dart',
  SQL = 'sql',
  HTML = 'html',
  CSS = 'css',
  JSON = 'json',
  YAML = 'yaml',
  XML = 'xml',
  SHELL = 'shell',
}